name: Build Artifacts
on:
  release:
    types: [created]
  push:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      publish_docker:
        description: "Publish image to ghcr.io/netcracker/qubership-query-exporter"
        type: boolean
        default: false
        required: false

env:
  TAG_NAME: ${{ github.event.release.tag_name || github.ref }}
  GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
  PUSH: ${{ github.event_name != 'workflow_dispatch' || inputs.publish_docker }}

jobs:
  multiplatform_build:
    strategy:
      fail-fast: false
      matrix:
        component:
          - name: qubership-query-exporter
            file: build/Dockerfile
            context: ""
    runs-on: ubuntu-24.04
    steps:
      - name: Validate
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" && "${{ github.ref }}" == refs/tags* ]]; then
            echo -e "\033[91mManual workflow run on tags is not allowed!\033[0m"
            exit 1
          fi
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${GITHUB_ACTOR}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Prepare Tag
        run: echo "TAG_NAME=$(echo ${TAG_NAME} | sed 's@refs/tags/@@;s@refs/heads/@@;s@/@_@g')" >> $GITHUB_ENV
      - name: Get package IDs for delete 
        id: get-ids-for-delete
        uses: Netcracker/get-package-ids@v0.0.1
        with:
          component-name: ${{ matrix.component.name }}
          component-tag: ${{ env.TAG_NAME }}
          access-token: ${{ secrets.GH_ACCESS_TOKEN }} 
        if: ${{ env.PUSH }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          no-cache: true
          context: ${{ matrix.component.context }}
          file: ${{ matrix.component.file }}
          platforms: linux/amd64 #,linux/arm64
          push: ${{ env.PUSH }}
          tags: ghcr.io/netcracker/${{ matrix.component.name }}:${{ env.TAG_NAME }}
          provenance: false
          secrets: |
            GH_ACCESS_TOKEN=${{ secrets.GH_ACCESS_TOKEN }}
      - uses: actions/delete-package-versions@v5
        with: 
          package-name: ${{ matrix.component.name }}
          package-type: 'container'
          package-version-ids: ${{ steps.get-ids-for-delete.outputs.ids-for-delete }}
        if: ${{ steps.get-ids-for-delete.outputs.ids-for-delete }}
