name: Add License Header
on:
  push:
    branches:
      - 'main'
env:
   COPYRIGHT_COMPANY: 'NetCracker Technology Corporation'
   COPYRIGHT_YEAR: '2024-2025'
jobs:
  license:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
      - run: docker run -v "${PWD}:/src" -i ghcr.io/google/addlicense -v -c "${{ env.COPYRIGHT_COMPANY }}" -y "${{ env.COPYRIGHT_YEAR }}" $(find . -type f -name "*.go" -o -type f -name "*.sh" -o -type f -name "*.py" | xargs echo)
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Auto-update license header
          branch: license-update
          title: Add License Header
          body: Automated license header update
          delete-branch: true